version: '3'

services:
  elkarbackup:
    #build: ./apache
    image: elkarbackup/elkarbackup:1.3.3-apache
    environment:
      SYMFONY__DATABASE__PASSWORD: "your-password-here"
      EB_CRON: "enabled"
    #volumes:
    #- backups:/app/backups
    #- uploads:/app/uploads
    #- sshkeys:/app/.ssh
    ports:
      - 8000:80
    
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: "your-password-here"
    volumes:
      - db:/var/lib/mysql

  client:
    image: elkarbackup/client

volumes:
  db:
#  backups:
#  uploads:
#  sshkeys:
